#!/bin/bash
BACKUP=./backup

mkdir -pv "$BACKUP"
touch "$BACKUP/remember_dotfiles_are_hidden"

function move_if_exists {
	if [ -e "$1" ] || [ -d "$1" ]; then
		if [ -L "$1" ] && echo -n "$1" | grep -F "$PWD"; then
			echo "(skipping already-installed $1)"
		elif ! mv -v "$1" "$BACKUP"; then
			echo "Failed to back up $1"
			exit 1
		fi
	fi
}

# first-time install tasks
if ! [ -d ~/.dotfiles_dir/ ]; then
	echo 'First-time install! Great'
	./get-fonts
	limp/install.sh
fi

move_if_exists ~/.vimrc
move_if_exists ~/.bashrc
move_if_exists ~/.vim
move_if_exists ~/.inputrc
move_if_exists ~/.gdbinit
move_if_exists ~/.nethackrc
move_if_exists ~/.gtkrc-2.0-kde4
move_if_exists ~/.Xmodmap
move_if_exists ~/.dotfiles_dir

ln -sv "$PWD/vim" ~/.vim
ln -sv "$PWD/vimrc" ~/.vimrc
ln -sv "$PWD/bashrc" ~/.bashrc
ln -sv "$PWD/inputrc" ~/.inputrc
ln -sv "$PWD/gdbinit" ~/.gdbinit
ln -sv "$PWD/nethackrc" ~/.nethackrc
ln -sv "/dev/null" ~/.gtkrc-2.0-kde4
ln -sv "$PWD/Xmodmap" ~/.Xmodmap
ln -sv "$PWD" ~/.dotfiles_dir

if ! [ -f user-aliases ]; then
	touch user-aliases
fi

if ! [ -d HyperSpec ]; then
	./get-hyperspec
fi
