#!/bin/bash
BACKUP=./backup

mkdir -pv "$BACKUP"
touch "$BACKUP/remember_dotfiles_are_hidden"

function do_install {
	if [ -e "$1" ] || [ -d "$1" ]; then
		if [ -L "$1" ] && readlink -f "$1" | grep -F "$2" &> /dev/null; then
			echo "(skipping already-installed $1)"
			return 0
		elif ! mv -v "$1" "$BACKUP"; then
			echo "Failed to back up $1"
			exit 1
		fi
	fi

	ln -sv "$2" "$1"
}

# first-time install tasks
if ! [ -d ~/.dotfiles_dir/ ]; then
	echo 'First-time install! Great'
	./bin/get-fonts
fi

do_install ~/.vimrc "$PWD/vimrc"
do_install ~/.bashrc "$PWD/bashrc"
do_install ~/.vim "$PWD/vim"
do_install ~/.inputrc "$PWD/inputrc"
do_install ~/.gdbinit "$PWD/gdbinit"
do_install ~/.nethackrc "$PWD/nethackrc"
do_install ~/.gtkrc-2.0-kde4 /dev/null
do_install ~/.Xmodmap "$PWD/Xmodmap"
do_install ~/.Xdefaults "$PWD/Xdefaults"
do_install ~/.i3 "$PWD/i3"
do_install ~/.dotfiles_dir "$PWD"

bin/install-powerline

if ! [ -f user-aliases ]; then
	touch user-aliases
fi

pip install i3-py
