#!/bin/bash
BACKUP=./backup

mkdir -pv "$BACKUP"
touch "$BACKUP/remember_dotfiles_are_hidden"

function do_install {
	if [ -e "$1" ] || [ -d "$1" ]; then
		if [ -L "$1" ] && readlink -f "$1" | grep -F $(readlink -f "$2") &> /dev/null; then
			echo "(skipping already-installed $1)"
			return 0
		elif ! mv -v "$1" "$BACKUP"; then
			echo "Failed to back up $1"
			exit 1
		fi
	fi

	ln -sv "$2" "$1"
}

# first-time install tasks
if ! [ -d ~/.dotfiles_dir/ ]; then
	echo 'First-time install! Great'
	./bin/get-fonts
	sudo -H pip install i3-py
fi

do_install ~/.vimrc "$PWD/vimrc"
do_install ~/.emacs "$PWD/emacs"
do_install ~/.bashrc "$PWD/bashrc"
do_install ~/.vim "$PWD/vim"
do_install ~/.gap "$PWD/gap"
do_install ~/.inputrc "$PWD/inputrc"
do_install ~/.gdbinit "$PWD/gdbinit"
do_install ~/.nethackrc "$PWD/nethackrc"
do_install ~/.gtkrc-2.0-kde4 /dev/null
do_install ~/.fonts.conf "$PWD/fonts.conf"
do_install ~/.Xmodmap "$PWD/Xmodmap"
do_install ~/.xbindkeysrc "$PWD/xbindkeysrc"
do_install ~/.XCompose "$PWD/XCompose"
do_install ~/.Xdefaults "$PWD/Xdefaults"
do_install ~/.xprofile "$PWD/xprofile"
do_install ~/.i3 "$PWD/i3"
do_install ~/.conkyrc "$PWD/conkyrc"
do_install ~/.dotfiles_dir "$PWD"

if ! [ -d ~/.fonts/powerline-fonts ]; then
	bin/install-powerline
fi

if ! [ -f user-aliases ]; then
	touch user-aliases
fi
