#!/bin/bash

function s? {
	if [ "$?" == "0" ]; then
		echo "ok"
	else
		echo "fail ($?)"
	fi
}

function aod {
	CMD=`history | tail -n 2 | head -n 1 | sed -e 's/^[0-9 ]* //'`
	alias $1=$CMD
}

function keepalias {
	CMD=`alias $1 | cut -d= -f2-`
	echo "alias $1=$CMD" >> ~/.dotfiles_dir/user-aliases
}

### Aliases
alias gpush="git push origin master"
alias ..="cd ..; pwd"
alias ls="ls --group-directories-first -C -w $(($COLUMNS / 2))"
alias l="ls --color -Fb"
alias ll="ls --color -Fl"
alias la="ls --color -Fa"
alias lla="ls --color -Fla"
# just in case
alias vi=vim

# load user aliases
source ~/.dotfiles_dir/user-aliases

### Environment
export PATH="$PATH:$DEVKITPPC/bin:$HOME/bin:$HOME/.local/bin"

if [ "$EDITOR" == "vi" ]; then
	export EDITOR=vim
fi

set -o vi
